apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-broker-auth"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-broker-resource"
data:
  username: {{ .Values.CfBrokerUsername | b64enc | quote }}
  password: {{ .Values.CfBrokerPassword | b64enc | quote }}